export const AuditAction = {
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGIN_FAILED: 'auth.login_failed',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_SESSION_REVOKE: 'auth.session_revoke',
  AUTH_SESSION_REVOKE_OTHERS: 'auth.session_revoke_others',
  USER_AVATAR_UPDATE: 'user.avatar_update',
  CONTACT_ADD: 'contact.add',
  CONTACT_REMOVE: 'contact.remove',
  CONVERSATION_CREATE_DIRECT: 'conversation.create_direct',
  CONVERSATION_CREATE_CHANNEL: 'conversation.create_channel',
  CONVERSATION_CREATE_GROUP: 'conversation.create_group',
  CONVERSATION_JOIN_INVITE: 'conversation.join_invite',
  CONVERSATION_LEAVE: 'conversation.leave',
  CONVERSATION_DELETE: 'conversation.delete',
  CONVERSATION_ADD_MEMBERS: 'conversation.add_members',
  CONVERSATION_REMOVE_MEMBER: 'conversation.remove_member',
  CONVERSATION_AVATAR_UPDATE: 'conversation.avatar_update',
  CONVERSATION_PIN: 'conversation.pin',
  CONVERSATION_UNPIN: 'conversation.unpin',
  MESSAGE_SEND: 'message.send',
  MESSAGE_SEND_ATTACHMENT: 'message.send_attachment',
  MESSAGE_EDIT: 'message.edit',
  MESSAGE_DELETE: 'message.delete',
  MESSAGE_REACTION: 'message.reaction',
  MESSAGE_FORWARD: 'message.forward',
  ADMIN_USER_UPDATE: 'admin.user_update',
  ADMIN_SESSION_REVOKE: 'admin.session_revoke',
  ADMIN_SESSION_REVOKE_ALL: 'admin.session_revoke_all',
  ATTACHMENT_UPLOAD: 'attachment.upload',
  ATTACHMENT_DOWNLOAD: 'attachment.download',
  ATTACHMENT_DELETE: 'attachment.delete',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
